#pragma once
#include "CoreMinimal.h"
#include "ECustomizationSlot.generated.h"

UENUM(BlueprintType)
namespace ECustomizationSlot {
    enum Type {
        EHeadSlot,
        EBodySlot,
        EUpperBodySlot,
        ELowerBodySlot,
        ECustomSlot1,
        ECustomSlot2,
        ECustomSlot3,
        ECustomSlot4,
        ECustomSlot5,
        ECustomSlot6,
        ECustomSlot7,
        ECustomSlot8,
        ECustomSlot9,
        ECustomSlot10,
        ECustomSlot11,
        ECustomSlot12,
        ECustomSlot13,
        ECustomSlot14,
        ECustomSlot15,
        ECustomSlot16,
        ECustomSlot17,
        ECustomSlot18,
        ECustomSlot19,
        ECustomSlot20,
        ECustomSlot21,
        ECustomSlot22,
        ECustomSlot23,
        ECustomSlot24,
        ECustomSlot25,
        ECustomSlot26,
        ECustomSlot27,
        ECustomSlot28,
        ECustomSlot29,
        ECustomSlot30,
        ECustomSlot31,
        ECustomSlot32,
        ECustomSlot33,
        ECustomSlot34,
        ECustomSlot35,
        ECustomSlot36,
        ECustomSlot37,
        ECustomSlot38,
        ECustomSlot39,
        ECustomSlot40,
        ECustomSlot41,
        ECustomSlot42,
        ECustomSlot43,
        ECustomSlot44,
        ECustomSlot45,
        ECustomSlot46,
        ECustomSlot47,
        ECustomSlot48,
        ECustomSlot49,
        ECustomSlot50,
        ECustomSlot51,
        ECustomSlot52,
        ECustomSlot53,
        ECustomSlot54,
        ECustomSlot55,
        ECustomSlot56,
        ECustomSlot57,
        ECustomSlot58,
        ECustomSlot59,
        ECustomSlot60,
        ECustomizationSlot_Max,
    };
}

