#pragma once
#include "CoreMinimal.h"
#include "ERsMotionSample.generated.h"

UENUM(BlueprintType)
enum ERsMotionSample {
    Time,
    AngularVelocityPitch = 0x2,
    AngularVelocityRoll,
    AngularVelocityYaw,
    LeanAngle = 0x1,
    ControllerInflexion = 0x5,
    RawControllerInputAngle,
    RelativeMotionYaw,
    RelativeMotionPitch,
    RelativeMotionRoll,
    ExpectedOrientationYaw,
    Speed,
    HorizontalSpeed,
    LocalSpeedX,
    LocalSpeedY,
    LocalSpeedZ,
    LocalMotionDirectionPitch,
    LocalMotionDirectionYaw,
    SlopeAngle,
    HeadingSlopeAngle,
    WorldOrientationPitch,
    WorldOrientationRoll,
    WorldOrientationYaw,
    LocalControllerDirectionYaw = 0x1F,
    ControllerIntent,
    LocalUndampedControllerDirectionYaw,
    UndampedControllerIntent,
    DistanceToGround = 0x17,
    TimeToGround,
    TimeToGroundLoss,
    RelativeGroundDirection,
    DistanceToWall,
    TimeToWall,
    TimeToWallLoss,
    RelativeWallDirection,
    SimRef_RelativeSpeed = 0x23,
    SimRef_RelativeHorizontalSpeed,
    SimRef_RelativeSpeedX,
    SimRef_RelativeSpeedY,
    SimRef_RelativeSpeedZ,
    SimRef_RelativeMotionDirectionPitch,
    SimRef_RelativeMotionDirectionYaw,
    SimRef_SlopeAngle,
    SimRef_HeadingSlopeAngle,
    SimRef_RelativeOrientationPitch,
    SimRef_RelativeOrientationRoll,
    SimRef_RelativeOrientationYaw,
    SimRef_RelativeControllerDirectionYaw = 0x37,
    SimRef_ControllerIntent,
    SimRef_RelativeUndampedControllerDirectionYaw,
    SimRef_UndampedControllerIntent,
    SimRef_DistanceToGround = 0x2F,
    SimRef_TimeToGround,
    SimRef_TimeToGroundLoss,
    SimRef_RelativeGroundDirection,
    SimRef_DistanceToWall,
    SimRef_TimeToWall,
    SimRef_TimeToWallLoss,
    SimRef_RelativeWallDirection,
    SimM_0_125_Speed = 0x3B,
    SimM_0_125_HorizontalSpeed,
    SimM_0_125_RelativeSpeedX,
    SimM_0_125_RelativeSpeedY,
    SimM_0_125_RelativeSpeedZ,
    SimM_0_125_RelativeMotionDirectionPitch,
    SimM_0_125_RelativeMotionDirectionYaw,
    SimM_0_125_SlopeAngle,
    SimM_0_125_HeadingSlopeAngle,
    SimM_0_125_RelativeOrientationPitch,
    SimM_0_125_RelativeOrientationRoll,
    SimM_0_125_RelativeOrientationYaw,
    SimM_0_125_RelativeControllerDirectionYaw = 0x4F,
    SimM_0_125_ControllerIntent,
    SimM_0_125_RelativeUndampedControllerDirectionYaw,
    SimM_0_125_UndampedControllerIntent,
    SimM_0_125_DistanceToGround = 0x47,
    SimM_0_125_TimeToGround,
    SimM_0_125_TimeToGroundLoss,
    SimM_0_125_RelativeGroundDirection,
    SimM_0_125_DistanceToWall,
    SimM_0_125_TimeToWall,
    SimM_0_125_TimeToWallLoss,
    SimM_0_125_RelativeWallDirection,
    SimM_0_25_Speed = 0x53,
    SimM_0_25_HorizontalSpeed,
    SimM_0_25_RelativeSpeedX,
    SimM_0_25_RelativeSpeedY,
    SimM_0_25_RelativeSpeedZ,
    SimM_0_25_RelativeMotionDirectionPitch,
    SimM_0_25_RelativeMotionDirectionYaw,
    SimM_0_25_SlopeAngle,
    SimM_0_25_HeadingSlopeAngle,
    SimM_0_25_RelativeOrientationPitch,
    SimM_0_25_RelativeOrientationRoll,
    SimM_0_25_RelativeOrientationYaw,
    SimM_0_25_RelativeControllerDirectionYaw = 0x67,
    SimM_0_25_ControllerIntent,
    SimM_0_25_RelativeUndampedControllerDirectionYaw,
    SimM_0_25_UndampedControllerIntent,
    SimM_0_25_DistanceToGround = 0x5F,
    SimM_0_25_TimeToGround,
    SimM_0_25_TimeToGroundLoss,
    SimM_0_25_RelativeGroundDirection,
    SimM_0_25_DistanceToWall,
    SimM_0_25_TimeToWall,
    SimM_0_25_TimeToWallLoss,
    SimM_0_25_RelativeWallDirection,
    SimM_0_5_Speed = 0x6B,
    SimM_0_5_HorizontalSpeed,
    SimM_0_5_RelativeSpeedX,
    SimM_0_5_RelativeSpeedY,
    SimM_0_5_RelativeSpeedZ,
    SimM_0_5_RelativeMotionDirectionPitch,
    SimM_0_5_RelativeMotionDirectionYaw,
    SimM_0_5_SlopeAngle,
    SimM_0_5_HeadingSlopeAngle,
    SimM_0_5_RelativeOrientationPitch,
    SimM_0_5_RelativeOrientationRoll,
    SimM_0_5_RelativeOrientationYaw,
    SimM_0_5_RelativeControllerDirectionYaw = 0x7F,
    SimM_0_5_ControllerIntent,
    SimM_0_5_RelativeUndampedControllerDirectionYaw,
    SimM_0_5_UndampedControllerIntent,
    SimM_0_5_DistanceToGround = 0x77,
    SimM_0_5_TimeToGround,
    SimM_0_5_TimeToGroundLoss,
    SimM_0_5_RelativeGroundDirection,
    SimM_0_5_DistanceToWall,
    SimM_0_5_TimeToWall,
    SimM_0_5_TimeToWallLoss,
    SimM_0_5_RelativeWallDirection,
    SimM_1_0_Speed = 0x83,
    SimM_1_0_HorizontalSpeed,
    SimM_1_0_RelativeSpeedX,
    SimM_1_0_RelativeSpeedY,
    SimM_1_0_RelativeSpeedZ,
    SimM_1_0_RelativeMotionDirectionPitch,
    SimM_1_0_RelativeMotionDirectionYaw,
    SimM_1_0_SlopeAngle,
    SimM_1_0_HeadingSlopeAngle,
    SimM_1_0_RelativeOrientationPitch,
    SimM_1_0_RelativeOrientationRoll,
    SimM_1_0_RelativeOrientationYaw,
    SimM_1_0_RelativeControllerDirectionYaw = 0x97,
    SimM_1_0_ControllerIntent,
    SimM_1_0_RelativeUndampedControllerDirectionYaw,
    SimM_1_0_UndampedControllerIntent,
    SimM_1_0_DistanceToGround = 0x8F,
    SimM_1_0_TimeToGround,
    SimM_1_0_TimeToGroundLoss,
    SimM_1_0_RelativeGroundDirection,
    SimM_1_0_DistanceToWall,
    SimM_1_0_TimeToWall,
    SimM_1_0_TimeToWallLoss,
    SimM_1_0_RelativeWallDirection,
    Ex_0_125_Speed = 0x9B,
    Ex_0_125_HorizontalSpeed,
    Ex_0_125_RelativeSpeedX,
    Ex_0_125_RelativeSpeedY,
    Ex_0_125_RelativeSpeedZ,
    Ex_0_125_RelativeMotionDirectionPitch,
    Ex_0_125_RelativeMotionDirectionYaw,
    Ex_0_125_SlopeAngle,
    Ex_0_125_HeadingSlopeAngle,
    Ex_0_125_RelativeOrientationPitch,
    Ex_0_125_RelativeOrientationRoll,
    Ex_0_125_RelativeOrientationYaw,
    Ex_0_125_RelativeControllerDirectionYaw = 0xAF,
    Ex_0_125_ControllerIntent,
    Ex_0_125_RelativeUndampedControllerDirectionYaw,
    Ex_0_125_UndampedControllerIntent,
    Ex_0_125_DistanceToGround = 0xA7,
    Ex_0_125_TimeToGround,
    Ex_0_125_TimeToGroundLoss,
    Ex_0_125_RelativeGroundDirection,
    Ex_0_125_DistanceToWall,
    Ex_0_125_TimeToWall,
    Ex_0_125_TimeToWallLoss,
    Ex_0_125_RelativeWallDirection,
    Ex_0_25_Speed = 0xB3,
    Ex_0_25_HorizontalSpeed,
    Ex_0_25_RelativeSpeedX,
    Ex_0_25_RelativeSpeedY,
    Ex_0_25_RelativeSpeedZ,
    Ex_0_25_RelativeMotionDirectionPitch,
    Ex_0_25_RelativeMotionDirectionYaw,
    Ex_0_25_SlopeAngle,
    Ex_0_25_HeadingSlopeAngle,
    Ex_0_25_RelativeOrientationPitch,
    Ex_0_25_RelativeOrientationRoll,
    Ex_0_25_RelativeOrientationYaw,
    Ex_0_25_RelativeControllerDirectionYaw = 0xC7,
    Ex_0_25_ControllerIntent,
    Ex_0_25_RelativeUndampedControllerDirectionYaw,
    Ex_0_25_UndampedControllerIntent,
    Ex_0_25_DistanceToGround = 0xBF,
    Ex_0_25_TimeToGround,
    Ex_0_25_TimeToGroundLoss,
    Ex_0_25_RelativeGroundDirection,
    Ex_0_25_DistanceToWall,
    Ex_0_25_TimeToWall,
    Ex_0_25_TimeToWallLoss,
    Ex_0_25_RelativeWallDirection,
    Ex_0_5_Speed = 0xCB,
    Ex_0_5_HorizontalSpeed,
    Ex_0_5_RelativeSpeedX,
    Ex_0_5_RelativeSpeedY,
    Ex_0_5_RelativeSpeedZ,
    Ex_0_5_RelativeMotionDirectionPitch,
    Ex_0_5_RelativeMotionDirectionYaw,
    Ex_0_5_SlopeAngle,
    Ex_0_5_HeadingSlopeAngle,
    Ex_0_5_RelativeOrientationPitch,
    Ex_0_5_RelativeOrientationRoll,
    Ex_0_5_RelativeOrientationYaw,
    Ex_0_5_RelativeControllerDirectionYaw = 0xDF,
    Ex_0_5_ControllerIntent,
    Ex_0_5_RelativeUndampedControllerDirectionYaw,
    Ex_0_5_UndampedControllerIntent,
    Ex_0_5_DistanceToGround = 0xD7,
    Ex_0_5_TimeToGround,
    Ex_0_5_TimeToGroundLoss,
    Ex_0_5_RelativeGroundDirection,
    Ex_0_5_DistanceToWall,
    Ex_0_5_TimeToWall,
    Ex_0_5_TimeToWallLoss,
    Ex_0_5_RelativeWallDirection,
    Ex_1_0_Speed = 0xE3,
    Ex_1_0_HorizontalSpeed,
    Ex_1_0_RelativeSpeedX,
    Ex_1_0_RelativeSpeedY,
    Ex_1_0_RelativeSpeedZ,
    Ex_1_0_RelativeMotionDirectionPitch,
    Ex_1_0_RelativeMotionDirectionYaw,
    Ex_1_0_SlopeAngle,
    Ex_1_0_HeadingSlopeAngle,
    Ex_1_0_RelativeOrientationPitch,
    Ex_1_0_RelativeOrientationRoll,
    Ex_1_0_RelativeOrientationYaw,
    Ex_1_0_RelativeControllerDirectionYaw = 0xF7,
    Ex_1_0_ControllerIntent,
    Ex_1_0_RelativeUndampedControllerDirectionYaw,
    Ex_1_0_UndampedControllerIntent,
    Ex_1_0_DistanceToGround = 0xEF,
    Ex_1_0_TimeToGround,
    Ex_1_0_TimeToGroundLoss,
    Ex_1_0_RelativeGroundDirection,
    Ex_1_0_DistanceToWall,
    Ex_1_0_TimeToWall,
    Ex_1_0_TimeToWallLoss,
    Ex_1_0_RelativeWallDirection,
    TargetLateralDistance = 0xFB,
    TargetLongitudinalDistance,
    TargetVerticalDistance,
    TargetLateralVelocity,
    TargetLongitudinalVelocity,
    TargetVerticalVelocity,
    TargetHorizontalAngle,
    ConstrainedMotionAngle,
    ConstrainedMotionSpeed,
    ConstrainedMotionDistance,
};

