#pragma once
#include "CoreMinimal.h"
#include "ERsVictimDataType.generated.h"

UENUM(BlueprintType)
enum class ERsVictimDataType : uint8 {
    EVDT_None,
    EVDT_MAX UMETA(Hidden),
    Archer,
    ATST,
    BlasterBolt,
    BountyHunter00,
    Boulder,
    BrawlerDroid,
    Bridge,
    Brute,
    Crab,
    Crate,
    Dagger,
    ElectroStaff,
    Flame,
    FlameBeetle,
    Flyer,
    Grenade,
    Grunt,
    HeavyGunner,
    Hero,
    Inquisitor,
    LVL_Cage_Large,
    LVL_Hammer,
    Missile,
    PopBall,
    Popper,
    ProbeDroid_AI,
    Pulverizer,
    Pulverizer_Dark,
    PushDoor,
    RocketLauncher,
    SlowdownFan,
    Slug,
    Spider,
    SpirePulv,
    StoneDoor,
    Windmill,
    ZeffoMedium,
    ZeffoMedium_NoTentacles,
    Zombie,
    NightBrotherMelee,
};

