#pragma once
#include "CoreMinimal.h"
#include "SwSplineSpeederBikeDrivingComponentPostNativeSplineSpeederBikeTickDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FSwSplineSpeederBikeDrivingComponentPostNativeSplineSpeederBikeTick, float, DeltaTime);

