#pragma once
#include "CoreMinimal.h"
#include "SwSplineSpeederBikeDrivingComponentOnVehicleFacingBackwardsDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_MULTICAST_DELEGATE(FSwSplineSpeederBikeDrivingComponentOnVehicleFacingBackwards);

