#pragma once
#include "CoreMinimal.h"
#include "ERsHeroInputFlags.generated.h"

UENUM(BlueprintType)
enum class ERsHeroInputFlags : uint8 {
    canAtk,
    canAtkAir,
    canAtkRelease,
    canAtkSpecial,
    canBalanceBeam,
    canBlock,
    canClimb,
    canAutoClimbGrab,
    canAutoCeilingClimb,
    canClimbRelease,
    canDoubleJump,
    canEvade,
    canFlashlight,
    canForcePull,
    canForcePush,
    canForceSlowdown,
    canHeal,
    canInput,
    canInteract,
    canJump,
    canLedgeGrab,
    canLedgeRelease,
    canLedgeDropDown,
    canMantle,
    canMonkeyClimb,
    canQuickRecover,
    canRope,
    canSheathe,
    canShimmy,
    canSlide,
    canSprint,
    canSwim,
    canSwimBoost,
    canTakeDmg,
    canTakeUnblockableDmg,
    canWallJump,
    canWallHang,
    canWallRun,
    canZTarget,
    canZipline,
    canZiplineJump,
    canDeathFromX,
    CanLightsaberSwitch,
    CanToggleWorldMap,
    CanFireBlaster,
    CanChargeBlaster,
    CanUseBDGun,
    CanUseSuper,
    CanMount,
    CanLiftSlam,
    CanBeastTame,
    CanMindTrick,
    CanPullSlash,
    CanForcePullDouble,
    CanForcePullDoubleSlam,
    CanDismount,
    CanGrapple,
    CanTripleJump,
    CanCigSummon,
    CanNavCancel,
};

