#pragma once
#include "CoreMinimal.h"
#include "ERsLedgeSurveyType.generated.h"

UENUM(BlueprintType)
namespace ERsLedgeSurveyType {
    enum Type {
        SURVEY_TYPE_SHIMMY_HORIZONTAL,
        SURVEY_TYPE_OUTSIDE_CORNER,
        SURVEY_TYPE_INSIDE_CORNER,
        SURVEY_TYPE_SHIMMY_VERTICAL,
        SURVEY_TYPE_LEAP_HORIZONTAL,
        SURVEY_TYPE_LEAP_VERTICAL,
        SURVEY_TYPE_ACTIVE,
        SURVEY_TYPE_MANTLE_VAULT,
        SURVEY_TYPE_FORCE_PULL,
        SURVEY_TYPE_DROP_DOWN,
        SURVEY_TYPE_AUXILIARY,
        SURVEY_TYPE_NAV_DETECTION,
        SURVEY_TYPE_REACH,
        SURVEY_TYPE_SHIMMY_RETARGET,
        SURVEY_TYPE_STORED_COUNT,
        SURVEY_TYPE_UNKNOWN = 0xE,
        SURVEY_TYPE_ATTACHED,
        SURVEY_TYPE_MAX UMETA(Hidden),
    };
}

