#pragma once
#include "CoreMinimal.h"
#include "ERsNavState.generated.h"

UENUM(BlueprintType)
enum class ERsNavState : uint8 {
    null,
    Ground,
    JumpPreAscend,
    JumpAscend,
    JumpCancelled,
    Fall,
    Glide,
    WallJumpAscend,
    Slide,
    LedgeHang,
    Rope,
    Swim,
    MonkeyBeam,
    BalanceBeam,
    BeamTransition,
    WallRun,
    Climb,
    Zipline,
    DebugFly,
    Cinematic,
    Meditation,
    Death,
    NavigationTransition,
    SpeederBike,
    Grapple,
    Quicksand,
    Vehicle,
    WallHang,
    PhaseDash,
    Mounted,
    Mounted_Ground,
    Mounted_Sprint,
    Mounted_PreJump,
    Mounted_Jump,
    Mounted_Fall,
    Mounted_Agitated,
    Glider_Air = 0x2B,
    Mounted_Spamel_Ground = 0x34,
    MARKDEBUGCLIMB,
    VehicleATAT,
    Claustrophobia,
    ConstrainedControl,
    Glider_Air_Reverse,
    NarrativeConstraints,
    Boosting,
    Mounted_Spamel_Air,
};

